Appease the linter.
The linter was complaining like this:
```
golangci-lint run
lib/aws/codebuild/build.go:91:2: QF1012: Use fmt.Fprintf(...) instead of WriteString(fmt.Sprintf(...)) (staticcheck)
    s.WriteString(fmt.Sprintf("Build %s\n%s\n%s\n", b.Arn.String(), b.Link(), b.ShortString(colorise)))
    ^
```

Applying the proposed solution fails like this:
```
cannot use s (variable of struct type strings.Builder) as io.Writer value in argument to fmt.Fprintf: strings.Builder does not implement io.Writer (method Write has pointer receiver)
```

Turns out you need to pass a pointer to `fmt.Fprintf`.
The linter documentation was fantastically unhelpful.
I have filed a [bug with upstream](https://github.com/dominikh/go-tools/issues/1701).